nodes:
  variant-opengwas:
    name: Variant
    files: 
      - opengwas/opengwas-tophits.csv
    script: nodes.variant.opengwas
    source: OpenGWAS-2020-10-13

  gwas-opengwas:
    name: Gwas
    files: 
      'meta': opengwas/opengwas-metadata-2020-10-13.csv
    script: nodes.gwas.opengwas
    source: OpenGWAS-2020-10-13

  gene-biomart:
    name: Gene
    files:
      'gene' : biomart/gene-data.txt-2020-10-13.gz
    script: nodes.gene.biomart
    source: BioMart-2020-10-13

  protein-biomart:
    name: Protein
    files:
      'protein' : biomart/protein-only-2020-10-13.txt
    script: nodes.protein.biomart
    source: BioMart-2020-10-13

  pathway-reactome:
    name: Pathway
    files:
      - reactome/ReactomePathways_human_2020-10-13.csv
    script: nodes.pathway.reactome
    source: Reactome-2020-10-13

  protein-reactome:
    name: Protein
    files:
      - reactome/UniProt2Reactome_All_Levels_human_2020-10-13.csv
    script: nodes.protein.reactome
    source: Reactome-2020-10-13 
    
rels:
  opengwas-gwas-variant:
    name: OPENGWAS_TOPHITS
    files:
      - opengwas/opengwas-tophits.csv
    script: rels.opengwas_tophits
    source: OpenGWAS-2020-07-16
  
  biomart-gene-protein:
    name: GENE_TO_PROTEIN 
    files:
      - biomart/protein-data-sp.txt.gz
    script: rels.gene_to_protein
    source: BioMart-2020-07-16

  variant-gene:
    name: VARIANT_TO_GENE
    files:
      - vep/variants-24-08-20.txt
    script: rels.variant_to_gene
    source: Ensembl-VEP-v37

  reactome-protein-pathway:
    name: PROTEIN_IN_PATHWAY
    files:
      - reactome/UniProt2Reactome_All_Levels_human_2020-10-13.csv
    script: rels.reactome_protein_pathway
    source: Reactome-2020-10-13

  reactome-pathway-pathway:
    name: PATHWAY_CHILD_OF
    files:
      - reactome/ReactomePathwaysRelation_human_2020-10-13.csv
    script: rels.reactome_pathway_pathway
    source: Reactome-2020-10-13



    
