name: Snakemake-lint

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.6.0
      with:
        directory: '.test'
        snakefile: 'workflow/Snakefile'
        args: '--lint --use-conda'
